apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: dp-mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      name: mysql
      labels:
        app: mysql
        type: pod
    spec:
      containers:
      - name: mysql
        image: mysql
        env:
        - name: MYSQL_DATABASE
          value: mysql-db
        - name: MYSQL_USER
          value: user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-password
              key: mysql_password
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-password
              key: mysql_root_password
        volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /db-data
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pvc
